REGISTER_USER = "REGISTER_USER"
GET_USER = "GET_USER"
REMOVE_USER = "REMOVE_USER"
LIST_USERS = "LIST_USERS"
ADD_WORKOUT = "ADD_WORKOUT"
LIST_WORKOUTS = "LIST_WORKOUTS"
FOLLOW_FRIEND = "FOLLOW_FRIEND"
SHOW_FRIEND_WORKOUTS = "SHOW_FRIEND_WORKOUTS"

# HTTP Methods
POST = "POST"
GET = "GET"
PUT = "PUT"
DELETE = "DELETE"